"""empty message

Revision ID: e8d33d39fa91
Revises: 
Create Date: 2022-04-17 14:39:21.155102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d33d39fa91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pair_mms_daily',
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('mms_20', sa.Float(), nullable=True),
    sa.Column('mms_50', sa.Float(), nullable=True),
    sa.Column('mms_200', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('pair', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pair_mms_daily')
    # ### end Alembic commands ###
